'use client';
import {useEffect,useRef,useState} from 'react';
const tracks={coaching:'Сопровождение: 8 встреч',vip:'VIP: персональный трек',meaning:'Цели и перегрузка',typology:'Типология и общение',ai:'Обучение ИИ',automation:'Боты и автоматизация',audit:'Отдельный разбор','9-sfer':'Результат «9 сфер»','one-layer':'Практика «Один слой»','one-layer-feedback':'Обратная связь по практике',book:'Книга','other-learning':'Другие занятия'};
export default function ApplicationForm(){const [track,setTrack]=useState('coaching');const [draft,setDraft]=useState('');const [copied,setCopied]=useState(false);const [error,setError]=useState('');const [source,setSource]=useState('');const output=useRef(null);
 useEffect(()=>{const q=new URLSearchParams(window.location.search);if(tracks[q.get('track')])setTrack(q.get('track'));setSource(['utm_source','utm_medium','utm_campaign','utm_content'].filter(k=>q.has(k)).map(k=>`${k}: ${q.get(k).slice(0,100)}`).join('\n'));},[]);
 useEffect(()=>{if(draft)output.current?.focus();},[draft]);
 function prepare(e){e.preventDefault();const f=new FormData(e.currentTarget);for(const name of ['task','result']){const field=e.currentTarget.elements.namedItem(name);field.setCustomValidity(String(f.get(name)).trim()?'':'Пожалуйста, напишите ответ.');if(!field.reportValidity())return;}setDraft(`Андрей, здравствуйте!\nИнтересует: ${tracks[track]}.\n\nМоя задача: ${String(f.get('task')).trim()}\nЖелаемое изменение: ${String(f.get('result')).trim()}\nЧто уже пробовал(а): ${String(f.get('tried')).trim()||'Пока не указано'}\nДоступное время: ${String(f.get('time')).trim()||'Хочу обсудить'}${source?'\n\nИсточник обращения:\n'+source:''}`);setCopied(false);setError('');}
 async function copy(){try{await navigator.clipboard.writeText(draft);setCopied(true);setError('');}catch{output.current?.focus();output.current?.select();setError('Выделите и скопируйте текст вручную: автоматическое копирование недоступно.');}}
 return <div className="application"><form onSubmit={prepare}><label htmlFor="track">Что вас интересует?</label><select id="track" value={track} onChange={e=>{setTrack(e.target.value);setDraft('');}}>{Object.entries(tracks).map(([key,value])=><option value={key} key={key}>{value}</option>)}</select><label htmlFor="task">Одна конкретная задача <span>обязательно</span></label><textarea id="task" name="task" onInput={e=>e.currentTarget.setCustomValidity('')} required maxLength={2000} rows={4} placeholder="Например: откладываю подготовку выступления или хочу освоить ИИ для рабочих текстов."/><label htmlFor="result">Что хотите получить? <span>обязательно</span></label><textarea id="result" name="result" onInput={e=>e.currentTarget.setCustomValidity('')} required maxLength={1200} rows={3} placeholder="Какое изменение сможете заметить или проверить?"/><label htmlFor="tried">Что уже пробовали?</label><textarea id="tried" name="tried" maxLength={1200} rows={2}/><label htmlFor="time">Сколько времени готовы выделять?</label><input id="time" name="time" maxLength={150} placeholder="Например: одна встреча в неделю и небольшие задания."/><p className="formHint">Не указывайте пароли, медицинские документы или сведения о других людях. Ответы используются здесь только для подготовки сообщения и не сохраняются после закрытия страницы.</p><button className="btn primary" type="submit">Подготовить сообщение</button></form><aside className="applicationAside"><p className="overline">КАК НАЧАТЬ</p><h2>Сначала задача.<br/>Затем формат.</h2><ol><li>Подготовьте сообщение.</li><li>Скопируйте текст.</li><li>Откройте Telegram или VK и отправьте Андрею.</li></ol><p>Обращение не обязывает вас покупать программу. Формат и условия обсудим в переписке.</p></aside>{draft&&<section className="draftBox" aria-labelledby="draftTitle"><h2 id="draftTitle">Сообщение готово к отправке</h2><p>Проверьте текст, скопируйте и вставьте его в личный чат. Сообщение ещё не отправлено.</p><label htmlFor="draft">Текст сообщения</label><textarea id="draft" ref={output} value={draft} onChange={e=>{setDraft(e.target.value);setCopied(false);}} rows={12}/><div className="draftActions"><button type="button" className="btn primary" onClick={copy}>{copied?'Текст скопирован':'Скопировать текст'}</button><a className="btn line" href="https://t.me/andreyjurievich" target="_blank" rel="noopener noreferrer">Открыть Telegram</a><a className="btn line" href="https://vk.ru/andrupsy" target="_blank" rel="noopener noreferrer">Открыть VK</a></div><p role="status">{error||(copied?'Вставьте текст в чат и нажмите «Отправить».':'Вы также можете скопировать текст вручную.')}</p><a className="textLink" href="/thank-you/">Я отправил(а) сообщение - что дальше?</a></section>}</div>}
