const fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'..');
const cards=['base','ege'].flatMap(n=>JSON.parse(fs.readFileSync(path.join(root,'public/catalog',n+'.json'),'utf8')));
const topics=[...new Set(cards.map(c=>c.topic))];
const meta=topics.map((topic,i)=>{const list=cards.filter(c=>c.topic===topic);const file=`deck-${i}.json`;fs.writeFileSync(path.join(root,'public/catalog',file),JSON.stringify(list));return {topic,count:list.length,file};});
fs.writeFileSync(path.join(root,'src/catalogMeta.ts'),'// Generated by scripts/split-catalog.cjs\nexport const CATALOG = '+JSON.stringify(meta,null,2)+';\n');
