// Generated by scripts/split-catalog.cjs
export const CATALOG = [
  {
    "topic": "Логика",
    "count": 300,
    "file": "deck-0.json"
  },
  {
    "topic": "Математика (5-9)",
    "count": 306,
    "file": "deck-1.json"
  },
  {
    "topic": "Искусственный интеллект",
    "count": 300,
    "file": "deck-2.json"
  },
  {
    "topic": "ЕГЭ Физика · Методы познания",
    "count": 7,
    "file": "deck-3.json"
  },
  {
    "topic": "ЕГЭ Физика · Механика",
    "count": 59,
    "file": "deck-4.json"
  },
  {
    "topic": "ЕГЭ Физика · Колебания и волны",
    "count": 16,
    "file": "deck-5.json"
  },
  {
    "topic": "ЕГЭ Физика · Тепловая физика",
    "count": 37,
    "file": "deck-6.json"
  },
  {
    "topic": "ЕГЭ Физика · Электричество",
    "count": 30,
    "file": "deck-7.json"
  },
  {
    "topic": "ЕГЭ Физика · Электромагнетизм",
    "count": 40,
    "file": "deck-8.json"
  },
  {
    "topic": "ЕГЭ Физика · Оптика",
    "count": 22,
    "file": "deck-9.json"
  },
  {
    "topic": "ЕГЭ Физика · Квантовая физика",
    "count": 15,
    "file": "deck-10.json"
  },
  {
    "topic": "ЕГЭ Физика · Современная физика",
    "count": 8,
    "file": "deck-11.json"
  },
  {
    "topic": "ЕГЭ Математика · Уравнения",
    "count": 21,
    "file": "deck-12.json"
  },
  {
    "topic": "ЕГЭ Математика · Неравенства",
    "count": 11,
    "file": "deck-13.json"
  },
  {
    "topic": "ЕГЭ Математика · Функции и производная",
    "count": 20,
    "file": "deck-14.json"
  },
  {
    "topic": "ЕГЭ Математика · Вероятность",
    "count": 21,
    "file": "deck-15.json"
  },
  {
    "topic": "ЕГЭ Математика · Планиметрия",
    "count": 20,
    "file": "deck-16.json"
  },
  {
    "topic": "ЕГЭ Математика · Стереометрия",
    "count": 21,
    "file": "deck-17.json"
  },
  {
    "topic": "ЕГЭ Математика · Текстовые задачи",
    "count": 20,
    "file": "deck-18.json"
  },
  {
    "topic": "ЕГЭ Математика · Последовательности",
    "count": 10,
    "file": "deck-19.json"
  },
  {
    "topic": "ЕГЭ Математика · Тригонометрия",
    "count": 3,
    "file": "deck-20.json"
  },
  {
    "topic": "ЕГЭ Математика · Параметры",
    "count": 2,
    "file": "deck-21.json"
  },
  {
    "topic": "ЕГЭ Математика · Числа и делимость",
    "count": 2,
    "file": "deck-22.json"
  },
  {
    "topic": "ЕГЭ Математика · Векторы",
    "count": 1,
    "file": "deck-23.json"
  }
];
