// Small arithmetic grammar: no eval, property access, assignments or executable code.
(function(root){
const H=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const substitutions=[[/\\cdot|\\times|[·×]/g,'*'],[/\\pi|π/g,'pi'],[/\\rho|ρ|\bро\b|\bro\b/g,'rho'],[/\\lambda|λ/g,'lambda'],[/\\nu|ν/g,'nu'],[/\\varepsilon|\\epsilon|ε|ℰ/g,'eps'],[/\\theta|θ/g,'theta'],[/\\alpha|α/g,'alpha'],[/\\mu|μ/g,'mu'],[/\\omega|ω/g,'omega'],[/\\Delta|Δ/g,'d'],[/Φ/g,'Phi'],[/φ/g,'phi'],[/δ/g,'delta'],[/Σ/g,'sum'],[/√/g,'sqrt'],[/₀/g,'0'],[/₁/g,'1'],[/₂/g,'2'],[/²/g,'^2'],[/³/g,'^3'],[/−/g,'-'],[/,/g,'.'],[/[{}]/g,m=>m==='{'?'(':')']];
function clean(s){s=s.replace(/ро/gi,'rho');for(const [r,v] of substitutions)s=s.replace(r,v);return s.replace(/\*\*/g,'^').replace(/[аАсСеЕмМтТхХ]/g,c=>({'а':'a','А':'A','с':'s','С':'S','е':'e','Е':'E','м':'m','М':'M','т':'t','Т':'T','х':'x','Х':'X'}[c])).replace(/_/g,'').replace(/\s+/g,'');}
function parse(s,variables){s=clean(s);if(s.length>300)throw Error('Слишком длинная запись');let pos=0;const names=[...new Set([...variables,'sqrt','sin','cos','abs','pi'])].sort((a,b)=>b.length-a.length);let tokens=[];
while(pos<s.length){const c=s[pos];if('+-*/^()='.includes(c)){tokens.push(c);pos++;continue;}const n=s.slice(pos).match(/^(?:\d+(?:\.\d*)?|\.\d+)/);if(n){tokens.push({n:+n[0]});pos+=n[0].length;continue;}
let name=names.find(n=>s.startsWith(n,pos));if(!name){const matches=names.filter(n=>s.slice(pos,pos+n.length).toLowerCase()===n.toLowerCase());const longest=matches.length?Math.max(...matches.map(n=>n.length)):0;const unique=matches.filter(n=>n.length===longest);if(unique.length===1)name=unique[0];}
if(!name)throw Error('Неизвестное обозначение: '+s.slice(pos,pos+12));tokens.push({v:name});pos+=name.length;if(name.length===1&&s[pos]==='2'&&!/[0-9.]/.test(s[pos+1]||'')){tokens.push('^',{n:2});pos++;}}
let i=0;const atomStart=t=>typeof t==='object'||t==='(';
function atom(){const t=tokens[i++];if(t==='+'||t==='-')return {op:'unary'+t,a:expr(25)};if(t==='('){const a=expr(0);if(tokens[i++]!==')')throw Error('Закрой скобку');return a;}if(t&&typeof t==='object'){if(t.n!==undefined)return t;if(['sqrt','sin','cos','abs'].includes(t.v)){if(tokens[i++]!=='(')throw Error('После функции нужны скобки');const a=expr(0);if(tokens[i++]!==')')throw Error('Закрой скобку');return {op:t.v,a};}return t;}throw Error('Ожидается число или буква');}
function expr(min){let a=atom();while(i<tokens.length){let op=tokens[i],implicit=atomStart(op);if(implicit)op='*';const bp={'+':10,'-':10,'*':20,'/':20,'^':30}[op];if(bp===undefined||bp<min)break;if(!implicit)i++;const b=expr(op==='^'?bp:bp+1);a={op,a,b};}return a;}
if(!tokens.length)throw Error('Пустой ответ');const left=expr(0);let right=null;if(tokens[i]==='='){i++;right=expr(0);}if(i!==tokens.length)throw Error('Проверь запись');return {left,right};}
function value(n,vars){if(n.n!==undefined)return n.n;if(n.v)return n.v==='pi'?Math.PI:vars[n.v];const a=value(n.a,vars),b=n.b?value(n.b,vars):0;switch(n.op){case '+':return a+b;case '-':return a-b;case '*':return a*b;case '/':return a/b;case '^':return a**b;case 'unary-':return -a;case 'unary+':return a;case 'sqrt':return Math.sqrt(a);case 'abs':return Math.abs(a);case 'sin':return Math.sin(a);case 'cos':return Math.cos(a);}}
const specs=[['rho',['rho','m','V'],'m/V'],['s',['s','v0','a','t'],'v0*t+a*t^2/2'],['F',['F','m','a'],'m*a'],['F',['F','G','m1','m2','r'],'G*m1*m2/r^2'],['M',['M','F','l'],'F*l'],['F',['F','rho','g','V'],'rho*g*V'],['p',['p','m','v'],'m*v'],['E',['E','m','v'],'m*v^2/2'],['T',['T','m','k'],'2*pi*sqrt(m/k)'],['v',['v','lambda','f'],'lambda*f'],['E',['E','k','T'],'3*k*T/2'],['p',['p','V','nu','R','T'],'nu*R*T/V'],['Q',['Q','dU','A'],'dU+A'],['Q',['Q','c','m','dT'],'c*m*dT'],['phi',['phi','p','ps'],'p/ps*100'],['F',['F','k','q1','q2','r'],'k*abs(q1*q2)/r^2'],['C',['C','q','U'],'q/U'],['I',['I','U','R'],'U/R'],['I',['I','eps','R','r'],'eps/(R+r)'],['F',['F','q','v','B','alpha'],'q*v*B*sin(alpha)'],['eps',['eps','N','dPhi','dt'],'N*dPhi/dt'],['T',['T','L','C'],'2*pi*sqrt(L*C)'],['c',['c','lambda','f'],'lambda*f'],['F',['F','a','b'],'a*b/(a+b)'],['delta',['delta','m','lambda'],'m*lambda'],['d',['d','theta','m','lambda'],'m*lambda/sin(theta)'],['K',['h','f','A','K'],'h*f-A'],['N',['N','N0','t','T'],'N0*2^(-t/T)'],['E0',['E0','m','c'],'m*c^2']];
function adapt(s,index){if(index===5)s=s.replace(/\bFa\b/g,'F');if(index===7)s=s.replace(/\bEk\b/g,'E');if(index===18)s=s.replace(/\bE\b/g,'eps');if(index===20)s=s.replace(/ΔΦ/g,'dPhi');if(index===24)s=s.replace(/Δ/g,'delta');if(index===28)s=s.replace(/^E\s*=/,'E0=');return s;}
function check(index,input){if(!String(input).trim())return {status:'blank'};const [target,vars,rhs]=specs[index];try{const p=parse(adapt(String(input),index),vars),expected=parse(rhs,vars).left;let sensitive=0;
const symbols=n=>n?[...(n.v?[n.v]:[]),...symbols(n.a),...symbols(n.b)]:[];
const missing=[...new Set(symbols(expected))].filter(v=>!symbols(p.left).concat(symbols(p.right)).includes(v));
const incorrect=()=>({status:'incorrect',message:missing.length?'В записи не хватает '+missing.join(', ')+'. '+(index===3&&missing.includes('m2')?'Сила зависит от обеих масс: в числителе нужны m1 и m2.'+(symbols(p.left).concat(symbols(p.right)).filter(v=>v==='m1').length>1?' Сейчас m1 записана дважды.':''):'Проверьте, что учтены все величины из вопроса.'):'Формула не совпадает с нужной зависимостью. Проверьте степени, знаки и скобки в знаменателе; сравните с образцом ниже.'});
for(let j=0;j<16;j++){const env={};vars.forEach((v,k)=>env[v]=0.7+((j*7+k*11+j*k*3)%31)/4+(j+1)*.017);if(index===26)env.h=10+env.h;if(index===27)env.N0+=20;env[target]=value(expected,env);const a=value(p.left,env),b=p.right?value(p.right,env):env[target];if(!Number.isFinite(a)||!Number.isFinite(b)||Math.abs(a-b)>1e-8*Math.max(1,Math.abs(a),Math.abs(b)))return incorrect();
if(p.right){env[target]=env[target]*1.137+.19;const da=value(p.left,env)-value(p.right,env);if(Number.isFinite(da)&&Math.abs(da)>1e-8)sensitive++;}}
if(p.right&&sensitive<12)return incorrect();return {status:'correct'};
}catch(e){return {status:'unrecognized',message:e.message};}}
const display={rho:'ρ',lambda:'λ',pi:'π',nu:'ν',eps:'ℰ',theta:'θ',alpha:'α',mu:'μ',omega:'ω',Phi:'Φ',phi:'φ',pathDelta:'Δ',delta:'δ',sum:'Σ',dU:'ΔU',dT:'ΔT',dPhi:'ΔΦ',dt:'Δt',g:'g',eta:'η',gamma:'γ',tau:'τ',sig:'σ',psi:'Ψ'};
function symbol(v){const subs={deltaM:['δ','m'],deltaRho:['δ','ρ'],deltaV:['δ','V'],eps0:['ε','0'],mu0:['μ','0'],omega0:['ω','0'],ac:['a','ц'],Fa:['F','А'],Fl:['F','Л'],Ftr:['F','тр'],XL:['X','L'],XC:['X','C'],Tx:['T','х'],Tn:['T','н'],ps:['p','нас']};if(subs[v])return `<msub><mi>${subs[v][0]}</mi><mi>${subs[v][1]}</mi></msub>`;if(display[v])return `<mi>${display[v]}</mi>`;const m=v.match(/^([A-Za-z]+)(\d+|[А-Яа-я]+)$/);return m?`<msub><mi>${H(m[1])}</mi><mn>${H(m[2])}</mn></msub>`:`<mi>${H(v)}</mi>`;}
function mathNode(n){if(n.n!==undefined)return `<mn>${n.n}</mn>`;if(n.v)return symbol(n.v);const a=mathNode(n.a),b=n.b?mathNode(n.b):'';switch(n.op){case '/':return `<mfrac><mrow>${a}</mrow><mrow>${b}</mrow></mfrac>`;case '^':return `<msup><mrow>${n.a.v||n.a.n!==undefined?a:'<mo>(</mo>'+a+'<mo>)</mo>'}</mrow><mrow>${b}</mrow></msup>`;case 'sqrt':return `<msqrt>${a}</msqrt>`;case 'abs':return `<mrow><mo>|</mo>${a}<mo>|</mo></mrow>`;case 'sin':case 'cos':return `<mrow><mi>${n.op}</mi><mo>(</mo>${a}<mo>)</mo></mrow>`;case 'unary-':return `<mrow><mo>−</mo>${a}</mrow>`;case 'unary+':return a;default:const wrap=(child,text)=>['+','-'].includes(child.op)&&n.op==='*'?`<mrow><mo>(</mo>${text}<mo>)</mo></mrow>`:text;return `<mrow>${wrap(n.a,a)}<mo>${n.op==='*'?'·':n.op==='-'?'−':n.op}</mo>${n.op==='-'&&['+','-'].includes(n.b.op)?`<mrow><mo>(</mo>${b}<mo>)</mo></mrow>`:wrap(n.b,b)}</mrow>`;}}
function typeset(text,extra=[]){try{const chunks=text.replace(/r(?:³|\^3)\/GM\b/g,'r^3/(G*M)').split('='),vars=[...new Set([...specs.flatMap(s=>s[1]),...extra,...Object.keys(display),'p1','p2','V1','V2','F1','F2','l1','l2','n1','n2','v','x','x0','r','R','L','C','B','S','U','I','W','P','M','A','Q','F','E','T','t','l','d','h','n','N','N0','v0','vmax','Imax','Umax','Qmax','Emax','I1','I2','U1','U2','N1','N2','XL','XC','nu0','omega0','deltaRho','deltaM','deltaV','eps0','mu0','Rn','Rr','Ftr','Fn','Fa','Fl','ac','m0','k','sig','eta','gamma','tau','E1','E2','dI','dV','dE','dm','Tn','Tx'])];return `<math xmlns="http://www.w3.org/1998/Math/MathML" display="block" aria-label="${H(text)}"><mrow>${chunks.map(c=>mathNode(parse(c,vars).left)).join('<mo>=</mo>')}</mrow></math>`;}catch{return `<span>${H(text)}</span>`;}}
root.PhysicsMath={parse,value,check,typeset,specs,clean};
})(typeof window==='undefined'?globalThis:window);
