
import {pages} from '../../lib/pages';
import {SiteHeader,SiteFooter,Cards,RouteCTA} from '../../components/SiteShell';
import ApplicationForm from '../../components/StaticForm';
import Catalog from '../../components/Catalog';
export const dynamicParams=false;
export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug}));}
export async function generateMetadata({params}){const {slug}=await params;const p=pages[slug];return p?{title:`${p.title} - Андрей Индыков`,description:p.lead,...(['apply','thank-you'].includes(slug)?{robots:{index:false,follow:true}}:{})}:{};}
export default async function RoutePage({params}){const {slug}=await params;const p=pages[slug];if(!p)throw new Error('Unknown route');return <main className={'routePage route-'+slug}><SiteHeader/><header className={'routeHero'+(p.image?' withImage':'')}><div><a className="crumb" href="/start/">Все направления</a><p className="overline">{p.tag}</p><h1>{p.title}</h1><p className="routeLead">{p.lead}</p>{p.facts&&<div className="routeFacts">{p.facts.map(f=><span key={f}>{f}</span>)}</div>}{p.primary&&<div className="routeActions"><a className="btn primary" href={p.primary.href} {...(p.primary.download?{download:true}:{})}>{p.primary.label}</a>{p.secondary&&<a className="btn line" href={p.secondary.href}>{p.secondary.label}</a>}</div>}</div>{p.image&&<img className="routePortrait" src={p.image} alt={slug==='book'?'Обложка книги «Какие бывают люди и бизнесы»':'Андрей Индыков'}/>}</header><div className="routeBody">{slug==='apply'&&<ApplicationForm/>}{slug==='catalog'&&<Catalog/>}{p.quote&&<blockquote className="caseQuote"><p>«{p.quote}»</p><cite>{p.author}</cite></blockquote>}{p.blocks&&<div className="detailBlocks" id="exercise">{p.blocks.map((b,i)=><section className="detailBlock" key={b.title}><span className="blockNumber">{String(i+1).padStart(2,'0')}</span><div><h2>{b.title}</h2>{b.text&&<p>{b.text}</p>}{b.items&&<ul>{b.items.map(x=><li key={x}>{x}</li>)}</ul>}</div></section>)}</div>}{p.note&&<aside className="routeNote">{p.note}</aside>}{p.cards&&<Cards items={p.cards}/>}</div>{p.cta!==false&&<RouteCTA {...p.cta}/>}<SiteFooter/></main>}
