import {apiUrl} from '../api';
import React,{useState,useEffect,useRef} from 'react';
import {createPortal} from 'react-dom';
import {UserAiConfig} from '../types';
interface Props {isOpen:boolean;onClose:()=>void;config:UserAiConfig;onSave:(c:UserAiConfig)=>void}
const presets=[
 {name:'VseGPT',format:'openai-compatible',endpoint:'https://api.vsegpt.ru/v1',link:'https://vsegpt.ru/Docs/API/Code'},
 {name:'RouterAI',format:'openai-compatible',endpoint:'https://routerai.ru/api/v1',link:'https://routerai.ru/docs/guides'},
 {name:'Knyazev AI',format:'openai-compatible',endpoint:'https://knyazevai.work/v1',link:'https://knyazevai.work/ai-api/'},
 {name:'Google Gemini',format:'gemini',endpoint:'https://generativelanguage.googleapis.com',link:'https://aistudio.google.com/apikey'},
 {name:'OpenRouter',format:'openai-compatible',endpoint:'https://openrouter.ai/api/v1',link:'https://openrouter.ai/settings/keys'},
 {name:'Groq',format:'openai-compatible',endpoint:'https://api.groq.com/openai/v1',link:'https://console.groq.com/keys'},
 {name:'DeepSeek',format:'openai-compatible',endpoint:'https://api.deepseek.com/v1',link:'https://platform.deepseek.com/api_keys'},
 {name:'OpenAI',format:'openai-compatible',endpoint:'https://api.openai.com/v1',link:'https://platform.openai.com/api-keys'},
] as const;
export function AiSettingsModal({isOpen,onClose,config,onSave}:Props){
 const [models,setModels]=useState<{id:string;name:string}[]>([]);
 const refreshModels=async()=>{setBusy(true);setResult('');try{const r=await fetch(apiUrl('/api/models'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({aiConfig:form})});const d=await r.json();if(!r.ok)throw Error(d.error);setModels(d.models);setResult('API доступен. Каталог обновлён: '+d.models.length+' моделей. Доступность генерации проверяется отдельно.');}catch(e){setResult(e instanceof Error?e.message:'Каталог недоступен');}finally{setBusy(false);}};
 const [form,setForm]=useState(config),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[result,setResult]=useState('');const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(isOpen){setModels([]);setForm(config);setResult('');dialog.current?.showModal();}else dialog.current?.close();},[isOpen]);
 const test=refreshModels;
 useEffect(()=>{if(!isOpen||!form.apiKey.trim())return;let live=true;const ctrl=new AbortController();const timer=setTimeout(async()=>{setBusy(true);try{const r=await fetch(apiUrl('/api/models'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({aiConfig:form}),signal:ctrl.signal});const d=await r.json();if(live){if(!r.ok)throw Error(d.error);setModels(d.models);setResult('Список моделей загружен автоматически: '+d.models.length+'. Генерация не проверялась.');}}catch(e){if(live)setResult(e instanceof Error?e.message:'Каталог недоступен');}finally{if(live)setBusy(false);}},1000);return()=>{live=false;clearTimeout(timer);ctrl.abort();setBusy(false);};},[isOpen,form.apiKey,form.endpoint,form.format]);
 return createPortal(<dialog ref={dialog} aria-label="Подключение своего ИИ" onCancel={onClose} onClick={e=>{if(e.target===dialog.current)onClose();}} className="m-auto w-[min(720px,95vw)] max-h-[90dvh] rounded-3xl p-6 sm:p-8 backdrop:bg-black/40 border border-zinc-200 overflow-y-auto"><form onSubmit={e=>{e.preventDefault();onSave({...form,endpoint:form.endpoint.trim(),apiKey:form.apiKey.trim(),model:form.model.trim()});onClose();}} className="space-y-5">
 <div className="flex justify-between gap-3"><h2 className="font-bold text-2xl">Подключение своего ИИ</h2><button type="button" aria-label="Закрыть настройки ИИ" onClick={onClose}>✕</button></div>
 <p className="text-sm text-zinc-600">Без ИИ работают карточки, повторение, награды и трекер. Для объяснений и создания новых карточек нужен API-ключ.</p>
 <div className="flex flex-wrap gap-2">{presets.map(p=><button key={p.name} type="button" disabled={busy} className="border rounded-xl p-2 text-sm" onClick={()=>{setModels([]);setResult('');setForm({...form,format:p.format,endpoint:p.endpoint,apiKey:'',model:p.name==='Knyazev AI'?'minimax-2.7':p.format==='gemini'?'gemini-3.8-flash':'',models:undefined,enabled:true});}}>{p.name}</button>)}</div>
 <label className="flex gap-2"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/>Использовать мой ключ</label>
 <label className="block">Формат<select className="block w-full p-3 border rounded-xl mt-1" value={form.format} onChange={e=>setForm({...form,format:e.target.value as UserAiConfig['format']})}><option value="openai-compatible">OpenAI-совместимый</option><option value="gemini">Google Gemini</option></select></label>
 <label className="block">Адрес API<input type="url" required className="block w-full p-3 border rounded-xl mt-1" value={form.endpoint} onChange={e=>setForm({...form,endpoint:e.target.value})}/></label>
 <p className="text-xs text-zinc-500">Для OpenAI-совместимого API укажите базовый адрес, обычно с /v1. Для Gemini используется официальный адрес Google. Собственные серверы разрешаются через AI_ALLOWED_ORIGINS на сервере приложения.</p>
 <label className="block">API-ключ<input autoComplete="off" type={show?'text':'password'} className="block w-full p-3 border rounded-xl mt-1" value={form.apiKey} onChange={e=>setForm({...form,apiKey:e.target.value})}/></label><button className="text-sm underline" type="button" onClick={()=>setShow(!show)}>{show?'Скрыть ключ':'Показать ключ'}</button>
 {form.endpoint.includes('knyazevai.work') && <p className="text-sm text-emerald-800">Модели по кругу: {(form.models||['minimax-2.7','deepseek-v4-flash','kimi-2.6']).filter(Boolean).join(', ')}. При перегрузке пробуем следующую. До 270 секунд на попытку, максимум три попытки.</p>}
 <label className="block">Модель<input list="provider-models" required className="block w-full p-3 border rounded-xl mt-1" placeholder="Идентификатор из кабинета провайдера" value={form.model} onChange={e=>setForm({...form,model:e.target.value})}/></label>
 <datalist id="provider-models">{models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</datalist><button type="button" disabled={busy} className="border rounded-xl p-3 text-sm" onClick={refreshModels}>Обновить модели у провайдера</button><p className="text-xs text-zinc-500">Список запрашивается напрямую у выбранного API. Выберите текстовую модель из списка или впишите точный ID. Каталог не проверяет баланс и доступность генерации.</p>
 {form.endpoint.includes('knyazevai.work')&&<label className="block text-sm">Модели для перебора (до трёх, через запятую)<input className="block w-full p-3 border rounded-xl mt-1" value={(form.models||['minimax-2.7','deepseek-v4-flash','kimi-2.6']).join(', ')} onChange={e=>setForm({...form,models:e.target.value.split(',').map(s=>s.trim()).slice(0,3)})}/></label>}
 <p className="text-xs text-zinc-500">Ключ хранится в текущей вкладке до её закрытия и передаётся серверу приложения для обращения к выбранному провайдеру. В резервную копию он не входит. Не вводите ключ в чужую копию приложения, которой не доверяете.</p>
 <details className="bg-amber-50 rounded-xl p-4 text-sm"><summary>Кто оплачивает запросы?</summary><p className="mt-3">С вашим ключом расходуются лимиты и баланс вашего API-проекта. Если владелец сервера явно включил общий ключ, запросы без личного ключа расходуют его лимиты. В этой сборке общий ключ по умолчанию отключён. Быстрая проверка запрашивает каталог моделей без генерации текста. Каталог может быть публичным, поэтому это не проверка баланса или права на генерацию.</p><p className="mt-2">Бесплатные квоты, модели и доступность зависят от провайдера. Обычная подписка на чат не гарантирует оплату API.</p><a className="underline block mt-2" href="https://ai.google.dev/gemini-api/docs/aistudio-build-mode" target="_blank" rel="noreferrer">Документация Google о публикации приложений</a></details>
 <details className="text-sm"><summary>Где получить ключ</summary>{presets.map(p=><a className="block underline my-2" key={p.name} href={p.link} target="_blank" rel="noreferrer">{p.name}: кабинет ключей</a>)}</details>
 <p role="status" className="text-sm">{result}</p><div className="flex flex-wrap gap-3"><button type="button" disabled={busy} onClick={test} className="border rounded-xl p-3">{busy?'Проверяю…':'Проверить соединение'}</button><button className="bg-emerald-800 text-white rounded-xl p-3">Сохранить</button></div>
 </form></dialog>,document.body);
}
