import {apiUrl} from '../api';
import React,{useState,useEffect} from 'react';
import {readCells,readHabits} from '../trackerStore';
const token=()=>{let t=localStorage.getItem('tracker_identity');if(!t){t=Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');localStorage.setItem('tracker_identity',t);}return t;};
async function api(action:string,body:unknown={}){const r=await fetch(apiUrl('/api/social/')+action,{method:'POST',headers:{'Content-Type':'application/json','x-tracker-token':token()},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'Ошибка сервера');return d;}
export async function syncSharedTracker(){if(localStorage.getItem('tracker_share_enabled')==='true')await api('sync',{name:localStorage.getItem('tracker_share_name')||'Андрей',habits:readHabits(),cells:readCells()});}
export function FriendsPanel({onView}:{onView:(value:any)=>void}){
 const [name,setName]=useState(()=>localStorage.getItem('tracker_share_name')||'Андрей'),[friends,setFriends]=useState<{id:string;name:string}[]>([]),[notice,setNotice]=useState(''),[link,setLink]=useState(''),[busy,setBusy]=useState(false),[invite,setInvite]=useState(()=>new URLSearchParams(location.hash.slice(1)).get('invite')||''),[inviter,setInviter]=useState(''),[consent,setConsent]=useState(false);
 const sync=()=>api('sync',{name,habits:readHabits(),cells:readCells()});
 const refresh=async()=>setFriends((await api('list')).friends);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setNotice('');try{await fn();}catch(e){setNotice(e instanceof Error?e.message:'Не удалось подключиться');}finally{setBusy(false);}};
 useEffect(()=>{refresh().catch(()=>{});if(invite)api('preview',{token:invite}).then(d=>setInviter(d.name)).catch(e=>setNotice(e.message));},[]);
 
 const share=async()=>{localStorage.setItem('tracker_share_name',name);await sync();localStorage.setItem('tracker_share_enabled','true');};
 return <details className="friends-panel" open={!!invite||undefined}><summary>♡ Учиться вместе <span>{friends.length?`${friends.length} друзей`:'Доступ только по согласию'}</span></summary><p>Приглашение открывает взаимный просмотр привычек, прошлых и будущих отметок. Карточки и API-ключи не передаются. Доступ можно отозвать.</p><label>Ваше имя <input maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Разрешаю принявшим приглашение друзьям смотреть мой трекер</label>
 {invite?<div className="invite-box"><b>{inviter?`${inviter} приглашает учиться вместе`:'Приглашение к совместному обучению'}</b><button disabled={busy||!consent||!inviter} onClick={()=>run(async()=>{await share();await api('accept',{token:invite});setInvite('');history.replaceState(null,'',location.pathname);await refresh();setNotice('Приглашение принято. Теперь ваши трекеры доступны друг другу.');})}>Принять приглашение</button><button onClick={()=>{setInvite('');history.replaceState(null,'',location.pathname);}}>Отказаться</button></div>:<button disabled={busy||!consent||!name.trim()} onClick={()=>run(async()=>{await share();const d=await api('invite');setLink(location.origin+location.pathname+'#invite='+d.token);setNotice('Ссылка действует 7 дней и принимается один раз.');})}>Создать приглашение</button>}
 {link&&<label>Скопируйте ссылку<input aria-label="Ссылка приглашения" readOnly value={link} onFocus={e=>e.target.select()}/><button onClick={()=>run(async()=>{await navigator.clipboard.writeText(link);setNotice('Ссылка скопирована.');})}>Копировать</button></label>}
 {location.hostname==='localhost'&&<small>Сейчас приложение работает локально. Ссылка localhost доступна только на этом компьютере. Для друзей на других устройствах позже понадобится общий сервер.</small>}
 <div className="friend-list">{friends.map(f=><div key={f.id}><b>{f.name}</b><button disabled={busy} onClick={()=>run(async()=>{onView(await api('view',{id:f.id}));})}>Смотреть трекер</button><button disabled={busy} onClick={()=>run(async()=>{await api('revoke',{id:f.id});onView(null);await refresh();})}>Отозвать доступ</button></div>)}</div><button disabled={busy} onClick={()=>run(refresh)}>Обновить друзей</button><p role="status">{notice}</p></details>;
}
