import React,{useEffect,useRef,useState} from 'react';
import {Flashcard} from '../types';
export interface PersonalReward {id:string;topic:string;title:string;threshold:number;earned?:boolean}
export interface PersonalProfile {name:string;address:string;rewards:PersonalReward[]}
export const rewardProgress=(r:PersonalReward,cards:Flashcard[])=>{const deck=cards.filter(c=>(c.topic===r.topic||c.originTopic===r.topic||c.ancestorTopics?.includes(r.topic))&&!c.deleted&&!c.pending);return deck.length?100*deck.filter(c=>c.mastery==='known').length/deck.length:0;};

export function TeacherGate({onClose,onUnlock}:{onClose:()=>void;onUnlock:()=>void}){
 const ref=useRef<HTMLDialogElement>(null),[code,setCode]=useState(''),[error,setError]=useState('');
 useEffect(()=>{ref.current?.showModal();},[]);
 return <dialog ref={ref} onCancel={onClose} className="doom-gate" aria-label="Вход для учителя"><form onSubmit={e=>{e.preventDefault();if(code.trim().toUpperCase()==='IDDQD')onUnlock();else setError('Доступ закрыт. Проверьте код.');}}><div className="doom-stripe"/><p className="doom-eyebrow">TEACHER ACCESS · LEVEL 01</p><h2>РЕЖИМ<br/>УЧИТЕЛЯ</h2><p>Редактирование колод и настройка наград откроются до закрытия этой вкладки.</p><label>Код доступа<input autoFocus type="password" autoComplete="off" value={code} onChange={e=>setCode(e.target.value)} maxLength={40}/></label><p role="alert">{error}</p><div className="flex gap-3"><button className="doom-enter">ОТКРЫТЬ ДОСТУП</button><button type="button" onClick={onClose}>Вернуться</button></div><small>Локальный родительский режим. Для общего сайта нужны отдельные учётные записи.</small></form></dialog>;
}

export function Personalization({profile,onSave,onClose,topics,cards,teacher,onTeacher,onLock}:{profile:PersonalProfile;onSave:(p:PersonalProfile)=>void;onClose:()=>void;topics:string[];cards:Flashcard[];teacher:boolean;onTeacher:()=>void;onLock:()=>void}){
 const [draft,setDraft]=useState(profile),[topic,setTopic]=useState(topics[0]||'');const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{ref.current?.showModal();},[]);
 const rewards=draft.rewards.filter(r=>r.topic===topic);
 const edit=(id:string,patch:Partial<PersonalReward>)=>setDraft({...draft,rewards:draft.rewards.map(r=>r.id===id?{...r,...patch}:r)});
 return <dialog ref={ref} onCancel={onClose} className="personal-dialog" aria-label="Персонализация"><form onSubmit={e=>{e.preventDefault();onSave({...draft,name:draft.name.trim()||'Ученик',address:draft.address.trim(),rewards:teacher?draft.rewards:profile.rewards});onClose();}}><header><div><span className="eyebrow">Ваш учебный маршрут</span><h2>Персонализация</h2></div><button type="button" onClick={onClose} aria-label="Закрыть персонализацию">✕</button></header><label>Имя<input maxLength={60} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Как к вам обращаться<input maxLength={80} placeholder="Например: Андрей, капитан, Саша" value={draft.address} onChange={e=>setDraft({...draft,address:e.target.value})}/></label><section className="parent-rewards"><h3>🎁 Награды за колоду</h3><p>Договоритесь о подарке или совместном занятии. До двух наград на колоду. Процент считается по усвоенным карточкам, включая самопроверку открытых вопросов.</p><label>Колода<select aria-label="Колода" value={topic} onChange={e=>setTopic(e.target.value)}>{[...new Set([...topics,...draft.rewards.map(r=>r.topic)])].map(t=><option key={t}>{t}</option>)}</select></label>{rewards.map(r=><div key={r.id} className="reward-edit"><label>Награда<input required disabled={!teacher||r.earned} maxLength={160} value={r.title} onChange={e=>edit(r.id,{title:e.target.value})}/></label><label>Порог, %<input type="number" min={1} max={100} step={1} required disabled={!teacher||r.earned} value={r.threshold} onChange={e=>edit(r.id,{threshold:Math.max(1,Math.min(100,Number(e.target.value)||1))})}/></label><span>{r.earned?'✓ Заслужена':`${Math.floor(rewardProgress(r,cards))}% из ${r.threshold}%`}</span>{teacher&&!r.earned&&<button type="button" onClick={()=>setDraft({...draft,rewards:draft.rewards.filter(x=>x.id!==r.id)})}>Удалить награду</button>}</div>)}{teacher?<button type="button" disabled={rewards.length>=2||!topic} onClick={()=>setDraft({...draft,rewards:[...draft.rewards,{id:crypto.randomUUID(),topic,title:'',threshold:80}]})}>+ Добавить награду ({rewards.length}/2)</button>:<button type="button" onClick={onTeacher}>🔒 Настроить награды: вход для родителя</button>}</section><div className="flex flex-wrap gap-3"><button className="primary-action">Сохранить</button>{teacher&&<button type="button" onClick={onLock}>Закрыть режим учителя</button>}</div></form></dialog>;
}
