import {AnswerSettings} from './AnswerSettings';
import {CardContent} from './CardContent';
import {parseBackup} from '../backup';
import React, { useState } from 'react';
import { Flashcard } from '../types';
interface Props { cards: Flashcard[]; onChange: (cards: Flashcard[])=>void }
const save=(name:string,text:string,type:string)=>{const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
export function TeacherView({cards,onChange}:Props){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[page,setPage]=useState(0);
 const [edit,setEdit]=useState<Flashcard|null>(null),[notice,setNotice]=useState('');
 const update=(id:string,patch:Partial<Flashcard>)=>onChange(cards.map(c=>c.id===id?{...c,...patch}:c));
 const visible=cards.filter(c=>(filter==='pending'?c.pending&&!c.deleted:filter==='deleted'?c.deleted:!c.deleted)&&`${c.topic} ${c.front} ${c.back}`.toLowerCase().includes(query.toLowerCase()));
 const objectives=[...new Set(cards.filter(c=>c.objective).map(c=>`${c.topic}|${c.objective}`))];
 const gaps=objectives.filter(key=>!cards.some(c=>`${c.topic}|${c.objective}`===key&&!c.deleted&&!c.pending&&c.quality!=='bad'));
 const csv=()=>{const rows=[['Тема','Вопрос','Ответ','Качество','Усвоение','Источник'],...cards.filter(c=>!c.deleted&&!c.pending).map(c=>[c.topic,c.front,c.back,c.quality||'',c.mastery||'',c.source||''])];save('cards.csv','\ufeff'+rows.map(r=>r.map(v=>'"'+v.replaceAll('"','""')+'"').join(';')).join('\r\n'),'text/csv;charset=utf-8');};
 const backup=()=>{const preferences:Record<string,string>={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)!;if(/^(study_(rewards|selected_topics|session_size|profile|split_parents|deck_facts)|mix_|repetitor_(tracker|deck_statuses|mix_completed))/.test(k))preferences[k]=localStorage.getItem(k)!;}save('smart-cards-backup.json',JSON.stringify({version:2,cards,preferences},null,2),'application/json');};
 const restore=async(file:File)=>{try{const data=parseBackup(await file.text());for(const [k,v] of Object.entries(data.preferences))localStorage.setItem(k,v);onChange(data.cards);setNotice('Карточки восстановлены. Обновите страницу, чтобы применить восстановленные настройки.');}catch(e){setNotice(e instanceof Error?e.message:'Ошибка импорта');}};
 return <div className="teacher-board max-w-[1500px] mx-auto p-4 sm:p-8"><span className="eyebrow">Мастерская знаний · ✎</span><h1 className="text-3xl font-semibold mb-2">Для учителя</h1><div className="teacher-flow"><button onClick={()=>{setFilter('pending');setPage(0);}}>✎ На проверке<strong>{cards.filter(c=>c.pending&&!c.deleted).length}</strong></button><span aria-hidden="true">↝</span><button onClick={()=>{setFilter('all');setPage(0);}}>✧ Учебная библиотека<strong>{cards.filter(c=>!c.deleted&&!c.pending).length}</strong></button><span aria-hidden="true">↝</span><div>♡ Уже усвоено<strong>{cards.filter(c=>c.mastery==='known'&&!c.deleted).length}</strong></div></div><p className="text-zinc-500 mb-5">{cards.length} карточек. Правки и предложения сохраняются в этом браузере.</p>
 <div className="flex flex-wrap gap-3 mb-5"><button className="border rounded-xl p-3 bg-emerald-50" onClick={()=>setEdit({id:crypto.randomUUID(),topic:'Моя колода',front:'',back:'',pending:true})}>Предложить карточку</button><button className="border rounded-xl p-3" onClick={csv}>Экспорт CSV</button><button className="border rounded-xl p-3" onClick={backup}>Резервная копия</button><label className="border rounded-xl p-3 cursor-pointer">Восстановить копию<input aria-label="Восстановить копию" type="file" accept="application/json" className="hidden" onChange={e=>{if(e.target.files?.[0])restore(e.target.files[0]);e.target.value='';}}/></label></div>
 <p role="status">{notice}</p>
 {!!gaps.length&&<details className="bg-amber-50 border rounded-xl p-4 my-4"><summary>Пробелы по целям обучения: {gaps.length}</summary><p className="text-sm my-2">Для этих целей не осталось одобренных карточек приемлемого качества. Это проверка заданных целей, а не полная оценка учебной программы.</p>{gaps.map(g=><button key={g} className="block text-left underline my-2" onClick={()=>{const [topic,objective]=g.split('|');setEdit({id:crypto.randomUUID(),topic,objective,front:objective+': ',back:'',pending:true});}}>{g.replace('|',' / ')}: предложить замену</button>)}</details>}
 <div className="flex gap-3 my-4"><input className="border rounded-xl p-3 flex-1 min-w-0" aria-label="Поиск карточек" placeholder="Тема, вопрос или ответ" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/><select className="border rounded-xl p-3" aria-label="Фильтр карточек" value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);}}><option value="all">Все</option><option value="pending">На проверке</option><option value="deleted">Удалённые</option></select></div>
 <div className="teacher-notes">{visible.slice(page*30,page*30+30).map((c,i)=><article key={c.id} className={'teacher-note note-'+i%4}><header><span>{c.topic}</span><span>{c.pending?'◌ На проверке':c.deleted?'Удалена':'✓ В библиотеке'}</span></header><div className="teacher-question"><CardContent card={c} answer={false} teacher/></div><details><summary>Ответ и объяснение</summary><CardContent card={c} answer teacher/></details><p className="note-source">{c.source}</p><footer><span>{c.mastery==='known'?'Знаю':c.mastery==='learning'?'Повторить':'Не изучена'} · {c.quality==='good'?'Хорошая':c.quality==='average'?'Средняя':c.quality==='bad'?'Плохая':'Без оценки'}</span><div><button onClick={()=>setEdit({...c})}>Редактировать</button>{c.pending&&<button onClick={()=>update(c.id,{pending:false,deleted:false})}>Одобрить</button>}<button onClick={()=>update(c.id,{deleted:!c.deleted})}>{c.deleted?'Восстановить':'Удалить'}</button></div></footer></article>)}</div>
 <div className="flex justify-between items-center my-4"><button disabled={page===0} onClick={()=>setPage(page-1)}>Назад</button><span>{visible.length} результатов · {page+1} / {Math.max(1,Math.ceil(visible.length/30))}</span><button disabled={(page+1)*30>=visible.length} onClick={()=>setPage(page+1)}>Далее</button></div>
 {edit&&<div role="dialog" aria-modal="true" aria-label="Редактор карточки" className="fixed inset-0 bg-black/40 z-[100] flex items-center justify-center p-4"><form className="bg-white rounded-2xl p-6 w-full max-w-3xl max-h-[90vh] overflow-auto space-y-4" onSubmit={e=>{e.preventDefault();if(!edit.front.trim()||!edit.back.trim()||!edit.topic.trim())return;onChange(cards.some(c=>c.id===edit.id)?cards.map(c=>c.id===edit.id?edit:c):[...cards,edit]);setEdit(null);setNotice('Сохранено. Новые предложения нужно одобрить перед обучением.');}}><h2 className="text-xl font-bold">Редактор карточки</h2><label className="block">Колода<input required className="border rounded p-2 w-full" value={edit.topic} onChange={e=>setEdit({...edit,topic:e.target.value})}/></label><label className="block">Вопрос<textarea required className="border rounded p-2 w-full" rows={3} value={edit.front} onChange={e=>setEdit({...edit,front:e.target.value})}/></label><label className="block">Ответ<textarea required className="border rounded p-2 w-full" rows={6} value={edit.back} onChange={e=>setEdit({...edit,back:e.target.value})}/></label><AnswerSettings card={edit} onChange={next=>setEdit({...next,hintsEdited:true})}/><div className="flex gap-3"><button className="bg-emerald-700 text-white rounded-xl p-3">Сохранить</button><button type="button" className="border rounded-xl p-3" onClick={()=>setEdit(null)}>Отмена</button></div></form></div>}
 </div>;
}
