import React,{useEffect,useState} from 'react';
import {Check,ChevronLeft,ChevronRight,Plus,Trash2,Sparkles} from 'lucide-react';
import {CellStatus,HabitItem,HABITS_KEY,readHabits,readCells,writeCells,dayKey,points} from '../trackerStore';
import {FriendsPanel} from './FriendsPanel';
import {HabitEditor} from './HabitEditor';
export type {CellStatus,HabitItem} from '../trackerStore';
export function TrackerView(){
 const [editingHabits,setEditingHabits]=useState(false);
 const [date,setDate]=useState(new Date()),[mode,setMode]=useState<'week'|'month'>('week'),[habits,setHabits]=useState(readHabits),[cells,setCells]=useState(readCells),[name,setName]=useState(''),[adding,setAdding]=useState(false),[undo,setUndo]=useState<Record<string,CellStatus>|null>(null);
 const [friend,setFriend]=useState<{name:string;habits:HabitItem[];cells:Record<string,CellStatus>}|null>(null);
 useEffect(()=>{const reload=()=>setCells(readCells());window.addEventListener('tracker-change',reload);window.addEventListener('storage',reload);return()=>{window.removeEventListener('tracker-change',reload);window.removeEventListener('storage',reload);};},[]);
 const today=dayKey(), start=new Date(date.getFullYear(),date.getMonth(),mode==='month'?1:date.getDate()-(date.getDay()+6)%7);
 const days=Array.from({length:mode==='week'?7:new Date(date.getFullYear(),date.getMonth()+1,0).getDate()},(_,i)=>new Date(start.getFullYear(),start.getMonth(),start.getDate()+i));
 const shownHabits=friend?.habits||habits, shownCells=friend?.cells||cells;
 const score=(h:HabitItem)=>days.reduce((n,d)=>n+(dayKey(d)<=today?points(shownCells[h.id+'_'+dayKey(d)]):0),0);
 const todayScore=shownHabits.reduce((n,h)=>n+points(shownCells[h.id+'_'+today]),0);
 const total=shownHabits.reduce((n,h)=>n+score(h),0),planned=shownHabits.reduce((n,h)=>n+days.filter(d=>dayKey(d)>today&&points(shownCells[h.id+'_'+dayKey(d)])>0).length,0);
 const change=(next:Record<string,CellStatus>)=>{setUndo(cells);writeCells(next);};
 const move=(n:number)=>setDate(mode==='month'?new Date(date.getFullYear(),date.getMonth()+n,1):new Date(date.getFullYear(),date.getMonth(),date.getDate()+7*n));
 const saveHabits=(next:HabitItem[])=>{setHabits(next);localStorage.setItem(HABITS_KEY,JSON.stringify(next));window.dispatchEvent(new Event('tracker-change'));};
 return <div className="tracker-page"><header className="tracker-hero"><div><span className="eyebrow">Маленькие шаги каждый день</span><h1>Мой ритм <Sparkles aria-hidden="true"/></h1><p>Даже половина дела уже имеет значение.</p></div><div className="tracker-sticker" aria-hidden="true">✦<br/><small>Ты здесь.<br/>Это начало!</small></div></header>
 <div className="tracker-stats"><div><small>Сегодня</small><strong>{todayScore.toLocaleString('ru')} <span>/ {shownHabits.length}</span></strong><progress value={todayScore} max={Math.max(1,shownHabits.length)}/></div><div><small>Баллы за период</small><strong data-testid="tracker-total">{total.toLocaleString('ru')}</strong><span>Сделано = 1 · Частично = 0,5</span></div><div><small>Впереди</small><strong>{planned} <span>отметок</span></strong><span>Планы не прибавляют баллы</span></div></div>
 <FriendsPanel onView={setFriend}/>
 {!friend&&<div className="tracker-habit-tools"><button onClick={()=>setEditingHabits(true)}>Редактор привычек</button></div>}
 {editingHabits&&!friend&&<HabitEditor habits={habits} onSave={saveHabits} onClose={()=>setEditingHabits(false)}/>}
 {friend&&<p className="friend-banner">Трекер: {friend.name}. Только просмотр. <button onClick={()=>setFriend(null)}>Вернуться к моему</button></p>}
 <div className="tracker-toolbar"><div className="tracker-segments">{(['week','month'] as const).map(m=><button key={m} aria-pressed={mode===m} onClick={()=>setMode(m)}>{m==='week'?'Неделя':'Месяц'}</button>)}</div><div className="tracker-navigation"><button aria-label={mode==='week'?'Предыдущая неделя':'Предыдущий месяц'} onClick={()=>move(-1)}><ChevronLeft size={18}/></button><button onClick={()=>setDate(new Date())}>Сегодня</button><button aria-label={mode==='week'?'Следующая неделя':'Следующий месяц'} onClick={()=>move(1)}><ChevronRight size={18}/></button></div><label>Перейти к дате <input aria-label="Перейти к дате" type="date" value={dayKey(date)} onChange={e=>{if(e.target.value)setDate(new Date(e.target.value+'T12:00:00'));}}/></label></div>
 <div className="tracker-period"><h2>{mode==='month'?date.toLocaleDateString('ru',{month:'long',year:'numeric'}):`${days[0].toLocaleDateString('ru',{day:'numeric',month:'short'})} → ${days[6].toLocaleDateString('ru',{day:'numeric',month:'short',year:'numeric'})}`}</h2><span>Нажатие: ✓ Сделано → ½ Частично → Пусто</span></div>
 <div className="tracker-grid-wrap"><table className={'tracker-grid '+mode}><thead><tr><th className="habit-heading">Привычка / Задача</th><th>Сумма</th>{days.map(d=><th key={dayKey(d)} className={dayKey(d)===today?'today':''}><small>{d.toLocaleDateString('ru',{weekday:'short'})}</small><b>{d.getDate()}</b></th>)}</tr></thead><tbody>{shownHabits.map((h,i)=><tr key={h.id}><th className="habit-heading"><span className="habit-dot" style={{background:['#75bba1','#a994ce','#efb966','#78aed2'][i%4]}}/>{h.name}{!friend&&h.id!=='h1'&&<button aria-label={'Удалить привычку '+h.name} onClick={()=>saveHabits(habits.filter(x=>x.id!==h.id))}><Trash2 size={13}/></button>}{h.id==='h1'&&<small>автоматически</small>}</th><td className="habit-score">{score(h).toLocaleString('ru')}</td>{days.map(d=>{const key=h.id+'_'+dayKey(d),s=shownCells[key]||'empty',future=dayKey(d)>today;return <td key={key}><button disabled={!!friend} aria-label={`${h.name}, ${d.getDate()}.${d.getMonth()+1}.${d.getFullYear()}: ${s}`} title={(future?'План: ':'')+({done:'Сделано, 1 балл',partial:'Частично, 0,5 балла',empty:'Пусто'}[s])} className={`tracker-cell ${s} ${future?'future':''} ${dayKey(d)===today?'today':''}`} onClick={()=>change({...cells,[key]:s==='empty'?'done':s==='done'?'partial':'empty'})}>{s==='done'?<Check size={18}/>:s==='partial'?<span>½</span>:null}</button></td>;})}</tr>)}</tbody></table></div>
 {!friend&&<div className="tracker-footer">{adding?<form onSubmit={e=>{e.preventDefault();if(name.trim()){saveHabits([...habits,{id:crypto.randomUUID(),name:name.trim(),category:'daily'}]);setName('');setAdding(false);}}}><input autoFocus aria-label="Название привычки" placeholder="Например, 20 минут чтения" value={name} maxLength={100} onChange={e=>setName(e.target.value)}/><button>Сохранить</button><button type="button" onClick={()=>setAdding(false)}>Отмена</button></form>:<button onClick={()=>setAdding(true)}><Plus size={16}/> Добавить привычку или цель</button>}<button disabled={!undo} onClick={()=>{if(undo){writeCells(undo);setUndo(null);}}}>Отменить отметку</button></div>}
 <p className="tracker-footnote">✧ Заход отмечается автоматически. Прошлое можно уточнять, будущее планировать. Баллы учитывают только дни до сегодня включительно.</p></div>;
}
